
abstract=
ontologyTitle=FAIR-O to FTR Alignment Module
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://w3id.org/fair-o/ftr-alignment
ontologyName=FAIR-O to FTR Alignment Module
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=2026-06-15
dateModified=
ontologyRevisionNumber=
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=https://creativecommons.org/licenses/by/4.0/
licenseIconURL=null
citeAs=Gabriele Tuozzo and Maria Angela Pellegrino. FAIR-O to FTR Alignment Module.
DOI=
status=Ontology Specification Draft
logo=
description=This module provides machine-readable mappings between FAIR-O and FTR without changing the FAIR-O core ontology. Since several concepts are related but not logically equivalent, skos:closeMatch is used instead of owl:equivalentClass.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Gabriele Tuozzo and Maria Angela Pellegrino
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=core;fair-o;FAIR-Vocabulary
importedOntologyURIs=http://www.w3.org/2004/02/skos/core;https://w3id.org/fair-o;https://w3id.org/fair/principles/terms/FAIR-Vocabulary
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=https://ostrails.github.io/FAIR_testing_resource_vocabulary/release/1.2.0/index-en.html
fundingGrants=
funders=
