
abstract=
ontologyTitle=FAIR-O: An Ontology for FAIR Assessment and Scoring
ontologyPrefix=fairo
ontologyNamespaceURI=https://w3id.org/fair-o#
ontologyName=FAIR-O: An Ontology for FAIR Assessment and Scoring
thisVersionURI=https://w3id.org/fair-o/1.0.0
latestVersionURI=
previousVersionURI=
dateCreated=2026-02-01
dateModified=2026-06-15
ontologyRevisionNumber=1.0
licenseURI=http://purl.org/NET/rdflicense/cc-by4.0
licenseName=Creative Commons CC-BY
licenseIconURL=null
citeAs=Gabriele Tuozzo and Maria Angela Pellegrino. FAIR-O: An Ontology for FAIR Assessment and Scoring. Revision: 1.0. Retrieved from: https://w3id.org/fair-o/1.0.0
DOI=10.5281/zenodo.20027101
status=Ontology Specification Draft
logo=https://raw.githubusercontent.com/GabrieleT0/FAIR-O-An-Ontology-for-FAIR-Assessment-and-Scoring/refs/heads/main/assets/logo.png
description=This ontology provides comprehensive FAIR assessment modeling. It reuses the official FAIR Vocabulary (https://w3id.org/fair/principles/terms/) for principle and sub-principle definitions.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Gabriele Tuozzo and Maria Angela Pellegrino
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=core
importedOntologyURIs=http://www.w3.org/2004/02/skos/core
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=https://raw.githubusercontent.com/GabrieleT0/FAIR-O-An-Ontology-for-FAIR-Assessment-and-Scoring/refs/heads/main/assets/diagram.png
source=
seeAlso=
fundingGrants=
funders=
